version: "3.9"
# services:
  # postgres:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_DB: mydb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # app:
  #   build: .
  #   environment:
  #     DATABASE_URL: postgresql://neondb_owner:npg_D6gqKkJPZbh8@ep-soft-fire-adwbstl1-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
  #     DB_SSL: "true"
  #     NODE_ENV: development
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules

# volumes:
#   postgres_data:


services:
  app:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_SSL: "true"
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    # Use different commands based on NODE_ENV
    command: >
      sh -c "if [ '$NODE_ENV' = 'development' ]; then
               npm run start:dev;
             else
               node dist/main.js;
             fi"

# Uncomment this if you want to run Postgres locally
# postgres:
#   image: postgres:16
#   environment:
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: mypassword
#     POSTGRES_DB: mydb
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   ports:
#     - "5432:5432"

# volumes:
#   postgres_data:
