version: "3.9"

services:
  app:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_SSL: "true"
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: >
      sh -c "if [ '$NODE_ENV' = 'development' ]; then
               npm run start:dev;
             else
               node dist/main.js;
             fi"
